// <auto-generated />
namespace FEE.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updatemultidb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatemultidb));
        
        string IMigrationMetadata.Id
        {
            get { return "202105160949453_update-multi-db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
