// <auto-generated />
namespace FEE.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updatetabletableslide : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatetabletableslide));
        
        string IMigrationMetadata.Id
        {
            get { return "202105121444260_update-table-table-slide"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
