// <auto-generated />
namespace FEE.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class donedbpart2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(donedbpart2));
        
        string IMigrationMetadata.Id
        {
            get { return "202105221712482_done-db-part-2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
